import colorama
print(colorama.Fore.RED + "Р" + colorama.Style.RESET_ALL)
print(colorama.Fore.BLUE + "і" + colorama.Style.RESET_ALL)
print(colorama.Fore.GREEN + "з" + colorama.Style.RESET_ALL)
print(colorama.Fore.BLACK + "н" + colorama.Style.RESET_ALL)
print(colorama.Fore.CYAN + "о" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTCYAN_EX + "к" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTMAGENTA_EX + "о" + colorama.Style.RESET_ALL)
print(colorama.Fore.MAGENTA + "л" + colorama.Style.RESET_ALL)
print(colorama.Fore.WHITE + "ь" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTYELLOW_EX + "о" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTBLUE_EX + "р" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTCYAN_EX + "о" + colorama.Style.RESET_ALL)
print(colorama.Fore.GREEN + "в" + colorama.Style.RESET_ALL)
print(colorama.Fore.WHITE + "и" + colorama.Style.RESET_ALL)
print(colorama.Fore.BLACK + "й" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTRED_EX + "" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTMAGENTA_EX + "т" + colorama.Style.RESET_ALL)
print(colorama.Fore.GREEN + "е" + colorama.Style.RESET_ALL)
print(colorama.Fore.RESET + "к" + colorama.Style.RESET_ALL)
print(colorama.Fore.LIGHTWHITE_EX + "с" + colorama.Style.RESET_ALL)
print(colorama.Fore.BLACK + "т" + colorama.Style.RESET_ALL)
print(colorama.Fore.GREEN + "!" + colorama.Style.RESET_ALL)


